import sqlite3

conn = sqlite3.connect("users.db")
cur = conn.cursor()

# Insert job roles
cur.execute("""
INSERT INTO job_role (role_name) VALUES
('Software Developer'),
('Web Developer'),
('Frontend Developer'),
('Backend Developer'),
('Full Stack Developer'),
('Python Developer'),
('Application Support Engineer'),
('Software Engineer'),
('System Engineer'),
('DevOps Engineer'),
('QA Engineer'),
('AI Engineer'),
('Machine Learning Engineer'),
('Cloud Engineer'),
('Tech Lead'),
('Software Architect'),
('Data Analyst'),
('Data Scientist'),
('Research Assistant'),
('Research Scientist'),
('Lab Technician'),
('Quality Analyst'),
('Statistician'),
('Accountant'),
('Finance Executive'),
('Bank Clerk'),
('Tax Consultant'),
('Auditor'),
('Finance Manager'),
('Senior Accountant'),
('Tax Advisor'),
('Marketing Executive'),
('Sales Executive'),
('HR Executive'),
('Business Development Executive'),
('Operations Executive'),
('Project Manager'),
('Business Analyst'),
('HR Manager'),
('Marketing Manager'),
('Operations Manager'),
('Product Manager'),
('Content Writer'),
('Teacher'),
('Journalist'),
('Social Worker'),
('Customer Support Executive'),
('Professor'),
('Content Strategist'),
('Editor'),
('Policy Analyst'),
('Technician'),
('Junior Engineer'),
('Site Supervisor'),
('Maintenance Engineer'),
('Intern'),
('Freelancer'),
('Consultant'),
('Project Coordinator'),
('Office Assistant')
""")

conn.commit()
print("Job roles inserted successfully!")